ospc-org/ospc-org.github.io

404.html

@Peter-Metz I was able to replicate the issue with runs not redirecting locally and resolve it with these changes.

Fix current domain definition

---

404.html

@Peter-Metz This just removes the print statements that I added in #4.

Remove extra logging

---

news_signup.md
newsletter.md
newsletter/01.24.2019_newsletter.md

Jan 24 Newsletter

---

team.md

Makes cards clickable to GH profiles. Changes organization affiliations to project affiliations

Modify team page

---

news_signup.md
newsletter.md
newsletter/02.20.2019_newsletter.md

February 20 newsletter

---

news_signup.md
newsletter.md
newsletter/03.20.2019_newsletter.md

Add March 20 OSPC newsletter

---

index.md

cc @Peter-Metz 
Thanks @donboyd5 for the report.

principal -> principle on home page

---

newsletter.md
newsletter/07.15.2020_newsletter.md

This PR adds the newsletter for July 15, 2020.

Add July 15, newsletter

---

newsletter.md
newsletter/07.29.2020_newsletter.md

This PR adds the OSPC Newsletter for July 29, 2020.

July 29 newsletter

---

newsletter.md
newsletter/08.12.2020_newsletter.md

This PR adds the newsletter for August 12, 2020.

August 12, 2020 newsletter

---

newsletter.md
newsletter/08.26.2020_newsletter.md

This PR adds the newsletter for August 26, 2020.

August 26 2020 newsletter

---

newsletter.md
newsletter/09.09.2020_newsletter.md

This PR includes the newsletter for September 9, 2020.

September 9, 2020 newsletter

---

newsletter.md
newsletter/09.23.2020_newsletter.md

This PR includes the September 23, 2020 newsletter.

9.23.20 newsletter

---

newsletter.md
newsletter/10.07.2020_newsletter.md

This PR adds the newsletter for October 7, 2020.
@Peter-Metz

October 7 2020 newsletter

---

newsletter.md
newsletter/10.21.2020_newsletter.md

This PR adds the newsletter for October 21, 2020.

October 21, 2020 newsletter

---

portfolio.md

This PR graduates all currently incubating projects.
@MattHJensen

Graduate all currently incubating projects

---

newsletter.md
newsletter/11.04.2020_newsletter.md

This PR adds the newsletter for November 4, 2020.
@Peter-Metz

November 4, 2020 newsletter

---

portfolio.md

This PR changes Vaccine-Efficacy's project status to `Incubating`. @Peter-Metz @MattHJensen 
Screenshot:

Change Vaccine-Efficacy to Incubating

---

newsletter.md
newsletter/11.18.2020_newsletter.md

This PR adds the newsletter for November 18, 2020.

Newsletter for November 18, 2020

---

newsletter.md
newsletter/12.09.2020_newsletter.md

This PR adds the newsletter for December 9, 2020.

December 9, 2020 newsletter

---

newsletter.md
newsletter/01.06.2021_newsletter.md

This PR adds the newsletter for January 6, 2021.

Newsletter for January 6, 2021

---

newsletter.md
newsletter/01.27.2021_newsletter.md

This PR adds the newsletter for January 27, 2021.

Newsletter for January 27 2021

---

newsletter.md
newsletter/02.10.2021_newsletter.md

This PR adds the newsletter for February 10, 2021.

February 10, 2021 Newsletter

---

newsletter.md
newsletter/02.24.2021_newsletter.md

This PR adds the newsletter for February 24, 2021.

February 24 newsletter

---

portfolio.md

Temporarily remove Vaccine-Flow-Model.

temp remove vaccine flow model

---

portfolio.md

Replace Vaccine-Flow-Model in portfolio to fix build.

replace vaccine flow

---

newsletter.md
newsletter/03.10.2021_newsletter.md

This PR adds the newsletter for March 10, 2021.

March 10, 2021 newsletter

---

newsletter.md
newsletter/03.24.2021_newsletter.md

This PR adds the newsletter for March 24, 2021.

Add March 24 2021 newsletter

---

newsletter.md
newsletter/04.07.2021_newsletter.md

This PR adds the newsletter for April 7, 2021.

Add newsletter for April 7 2021

---

_includes/header.html
newsletter.md

remove signup in newsletter
